task01:
	g++ -o task01.out task01.cpp
task02:
	g++ -o task02.out task02.cpp
task03:
	g++ -o task03.out task03.cpp
task04:
	g++ -o task04.out task04.cpp
all: task01 task02 task03 task04

clean:
	rm -f task01.out task02.out task03.out task04.out